/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '//auth/login': RouteRecordInfo<
      '//auth/login',
      '/auth/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//auth/pending': RouteRecordInfo<
      '//auth/pending',
      '/auth/pending',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//auth/register': RouteRecordInfo<
      '//auth/register',
      '/auth/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//auth/rejected': RouteRecordInfo<
      '//auth/rejected',
      '/auth/rejected',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//dashboard/': RouteRecordInfo<
      '//dashboard/',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//families/': RouteRecordInfo<
      '//families/',
      '/families',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//families/[id]/': RouteRecordInfo<
      '//families/[id]/',
      '/families/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '//families/[id]/edit': RouteRecordInfo<
      '//families/[id]/edit',
      '/families/:id/edit',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '//families/deferred/new': RouteRecordInfo<
      '//families/deferred/new',
      '/families/deferred/new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//families/new': RouteRecordInfo<
      '//families/new',
      '/families/new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//families/sheet-builder': RouteRecordInfo<
      '//families/sheet-builder',
      '/families/sheet-builder',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//permissions/': RouteRecordInfo<
      '//permissions/',
      '/permissions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//permissions/[userId]': RouteRecordInfo<
      '//permissions/[userId]',
      '/permissions/:userId',
      { userId: ParamValue<true> },
      { userId: ParamValue<false> },
      | never
    >,
    '//profile/': RouteRecordInfo<
      '//profile/',
      '/profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//profile/[userId]': RouteRecordInfo<
      '//profile/[userId]',
      '/profile/:userId',
      { userId: ParamValue<true> },
      { userId: ParamValue<false> },
      | never
    >,
    '//timesheet/': RouteRecordInfo<
      '//timesheet/',
      '/timesheet',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//timesheet/all': RouteRecordInfo<
      '//timesheet/all',
      '/timesheet/all',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//volunteers/': RouteRecordInfo<
      '//volunteers/',
      '/volunteers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//volunteers/[id]': RouteRecordInfo<
      '//volunteers/[id]',
      '/volunteers/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/features/auth/pages/login.vue': {
      routes:
        | '//auth/login'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/auth/pages/pending.vue': {
      routes:
        | '//auth/pending'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/auth/pages/register.vue': {
      routes:
        | '//auth/register'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/auth/pages/rejected.vue': {
      routes:
        | '//auth/rejected'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/dashboard/pages/index.vue': {
      routes:
        | '//dashboard/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/families/pages/index.vue': {
      routes:
        | '//families/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/families/pages/[id]/index.vue': {
      routes:
        | '//families/[id]/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/families/pages/[id]/edit.vue': {
      routes:
        | '//families/[id]/edit'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/families/pages/deferred/new.vue': {
      routes:
        | '//families/deferred/new'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/families/pages/new.vue': {
      routes:
        | '//families/new'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/families/pages/sheet-builder.vue': {
      routes:
        | '//families/sheet-builder'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/permissions/pages/index.vue': {
      routes:
        | '//permissions/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/permissions/pages/[userId].vue': {
      routes:
        | '//permissions/[userId]'
      views:
        | never
      pathParamNames:
        | 'userId'
    }
    'src/features/profile/pages/index.vue': {
      routes:
        | '//profile/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/profile/pages/[userId].vue': {
      routes:
        | '//profile/[userId]'
      views:
        | never
      pathParamNames:
        | 'userId'
    }
    'src/features/timesheet/pages/index.vue': {
      routes:
        | '//timesheet/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/timesheet/pages/all.vue': {
      routes:
        | '//timesheet/all'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/volunteers/pages/index.vue': {
      routes:
        | '//volunteers/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/features/volunteers/pages/[id].vue': {
      routes:
        | '//volunteers/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
